whatchareadn/main/urls.py
from django.urls import path
from .views import Index, Search, Library
from . import views

app_name = 'main'

urlpatterns = [
        path('', Index.as_view(), name='index'),
        path('search/', Search.as_view(), name='search'),
        path('library/', Library.as_view(), name='library'),
        path('search/add_book/', views.add_book_view, name='add'),
        path('library/delete_book/', views.delete_book_view, name='delete'),
        path('test/', views.testpage_view, name='test'),
        path('library/shelf/', views.get_shelf, name='shelf'),
        path('library/change_shelf/', views.change_shelf, name='change-shelf'),
        path('book_detail/', views.get_book_detail, name='bookdetail'),
        path('library/delete_shelf/', views.delete_shelf, name='delete-shelf'),
        path('library/create_shelf/', views.create_shelf, name='create-shelf'),

]

whatchareadn/whatchareadn/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('main.urls', namespace='main')),
    path("users/", include('django.contrib.auth.urls')),
    path("users/", include('users.urls', namespace='users')),
]

whatchareadn/main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Shelf(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=250)
    count = models.IntegerField(default=0)

    def __str__(self):
        return self.name


class Book(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    selflink = models.URLField(max_length=1000, null=True, blank=True)
    title = models.CharField(max_length=250)
    authors = models.CharField(max_length=250, null=True, blank=True)
    isbn10 = models.CharField(max_length=10, null=True, blank=True)
    isbn13 = models.CharField(max_length=13, null=True, blank=True)
    description = models.CharField(max_length=20000, null=True, blank=True)
    googleid = models.CharField(max_length=250)
    image_link = models.URLField(max_length=1000, null=True, blank=True)
    have_read = models.BooleanField(default=False)
    reading = models.BooleanField(default=False)
    owned = models.BooleanField(default=False)
    shelf = models.ForeignKey(Shelf, related_name='books', null=True, blank=True, on_delete=models.SET_NULL)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title
    

whatchareadn/main/views.py
# vim:foldmethod=marker
from django.shortcuts import render, redirect
from django.urls import reverse

from django.views import View
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse

from .models import Book, Shelf
import requests
import json


############################
# PAGES
############################

############################
# Home page view {{{
class Index(View):

    def get(self, request):
        r = requests.get('https://www.googleapis.com/books/v1/volumes/h4hHEAAAQBAJ', params=request.GET)
        stuffs = json.loads(r.text)

        isbns = stuffs["volumeInfo"]["industryIdentifiers"]
        for i in isbns:
            a = i['type']
            b = i['identifier']
            if a == 'ISBN_13':
                isbn13 = b
        for i in isbns:
            a = i['type']
            b = i['identifier']
            if a == 'ISBN_10':
                isbn10 = b
        print(isbn10)
        print(isbn13)


        context = {
        }

        return render(request, 'main/index.html', context)
# }}}

############################
# Search page view {{{
class Search(View):

    def get(self, request):
        context = {
        }
        return render(request, 'main/search.html', context)

    def post(self, request):
        cur_user = request.user

        if 'titlebtn' in request.POST:
            searched = request.POST['titleSearch']

            r = requests.get('https://www.googleapis.com/books/v1/volumes?q=' + searched + '&maxResults=40', params=request.GET)
            print(r.text)
            stuff = json.loads(r.text)
            books = list(Book.objects.filter(owner=cur_user).values_list('title', flat=True))

            context = {
                    'stuff': stuff,
                    'books': books,
            }

            return render(request, 'main/search.html', context)

        elif 'authorbtn' in request.POST:
            searched = request.POST['authorSearch']

            r = requests.get('https://www.googleapis.com/books/v1/volumes?q=inauthor:' + searched, params=request.GET)
            print(r.text)
            stuff = json.loads(r.text)
            books = list(Book.objects.all().values_list('title', flat=True))

            context = {
                    'stuff': stuff,
                    'books': books,
            }

            return render(request, 'main/search.html', context)

        elif 'googleidbtn' in request.POST:
            searched = request.POST['googleidSearch']

            r = requests.get('https://www.googleapis.com/books/v1/volumes/' + searched, params=request.GET)
            print(r.text)
            stuffs = json.loads(r.text)
            books = list(Book.objects.all().values_list('title', flat=True))

            context = {
                    'stuffs': stuffs,
                    'books': books,
            }

            return render(request, 'main/search.html', context)
# }}}

############################
# Library page view {{{
class Library(View):

    def get(self, request):

        cur_user = request.user
        library = Book.objects.filter(owner=cur_user)
        shelves = Shelf.objects.filter(owner=cur_user)


        return render(request, 'main/library.html', {'library': library,
                                                      'shelves': shelves,
                                                     })
# }}}

############################
# Test page view {{{
def testpage_view(request):
        cur_user = request.user
        library = Book.objects.filter(owner=cur_user)
        shelves = Shelf.objects.all()
        return render(request, 'main/testpage.html', {'library': library,
                                                      'shelves': shelves,
                                                    })
# }}}


############################
# FUNCTIONS
############################

############################
# Add book to library  {{{
def add_book_view(request):
    searched = request.POST['addid']
    if request.method == "POST":
        r = requests.get('https://www.googleapis.com/books/v1/volumes/' + searched, params=request.GET)
        print(r.text)
        stuffs = json.loads(r.text)
        print(stuffs)

        try:
            shelf = Shelf.objects.get(owner=request.user, name="Not on Shelf")
        except:
            new_shelf = Shelf(
                              owner = request.user,
                              name = "Not on Shelf",
                             )
            new_shelf.save()
            shelf = Shelf.objects.get(owner=request.user, name="Not on Shelf")


        title = stuffs["volumeInfo"]["title"]
        selflink = stuffs["selfLink"]
        authorlist = stuffs["volumeInfo"]["authors"]
        for author in authorlist:
            authors = ""
            authors += author
        if "description" in stuffs["volumeInfo"]:
            description = stuffs["volumeInfo"]["description"]
        else:
            description = "description"
        googleid = stuffs["id"]
        image_link = stuffs["volumeInfo"]["imageLinks"]["thumbnail"]
        if "industryIdentifiers" in stuffs["volumeInfo"]:
            isbns = stuffs["volumeInfo"]["industryIdentifiers"]
            for i in isbns:
                a = i['type']
                b = i['identifier']
                if a == 'ISBN_13':
                    isbn13a = b
            for i in isbns:
                a = i['type']
                b = i['identifier']
                if a == 'ISBN_10':
                    isbn10a = b
            if isbn13a:
                isbn13 = isbn13a
            else:
                isbn13 = "no ISBN13"
            if isbn10a:
                isbn10 = isbn10a
            else:
                isbn10 = "no ISBN10"
        else:
            isbn13 = "no ISBN13"
            isbn10 = "no ISBN10"

        new_book = Book(
                        owner = request.user,
                        selflink = selflink,
                        title = title,
                        authors = authors,
                        isbn10 = isbn10,
                        isbn13 = isbn13,
                        description = description,
                        googleid = googleid,
                        image_link = image_link,
                        shelf = shelf,
                        )
        new_book.save()

        return HttpResponse('Yo')
# }}}


############################
# Delete a book from the Book database table{{{
def delete_book_view(request):
    cur_user = request.user
    buttid = request.POST['buttid']
    if request.method == "POST":
        Book.objects.filter(owner=cur_user, googleid=buttid).delete()
        return HttpResponse('Yo')
# }}}

############################
# Change the shelf for a book{{{
def change_shelf(request):
    cur_user = request.user
    shelfn = request.POST['shelfn']
    bookid = request.POST['bookid']
    if request.method == "POST":
        obj = Book.objects.get(googleid=bookid, owner=cur_user)
        shelf = Shelf.objects.get(name=shelfn, owner=cur_user)
        obj.shelf = shelf
        obj.save()
        return HttpResponse('Yo')
# }}}

############################
# Change the shelf that you are viewing in the library{{{
def get_shelf(request):
    cur_user = request.user
    shelfname = request.POST['shelf']
    if request.method == "POST":
        if shelfname == "All":
            bookshelf = Book.objects.filter(owner=cur_user)
            shelflist = Shelf.objects.filter(owner=cur_user)
            return JsonResponse({'books': list(bookshelf.values()), 'shelves': list(shelflist.values())})
        else:
            nameshelf = Shelf.objects.get(name=shelfname, owner=cur_user)
            bookshelf = Book.objects.filter(owner=cur_user, shelf=nameshelf)
            shelflist = Shelf.objects.filter(owner=cur_user)
            return JsonResponse({'books': list(bookshelf.values()), 'shelves': list(shelflist.values())})
# }}}

############################
# Get book info from the api for the detail modal{{{
def get_book_detail(request):
    searched = request.POST['btnid']
    if request.method == "POST":
        r = requests.get('https://www.googleapis.com/books/v1/volumes/' + searched, params=request.GET)
        print(r.text)
        bookdetail = json.loads(r.text)
        print(bookdetail)

        title = bookdetail["volumeInfo"]["title"]
        if "publisher" in bookdetail["volumeInfo"]:
            publisher = bookdetail["volumeInfo"]["publisher"]
        else:
            publisher = "Not found"
        if "publishedDate" in bookdetail["volumeInfo"]:
            pubdate = bookdetail["volumeInfo"]["publishedDate"]
        else:
            pubdate = "Not found"
        selflink = bookdetail["selfLink"]
        authorlist = bookdetail["volumeInfo"]["authors"]
        for author in authorlist:
            authors = ""
            authors += author
        if "description" in bookdetail["volumeInfo"]:
            description = bookdetail["volumeInfo"]["description"]
        else:
            description = "description"
        googleid = bookdetail["id"]
        image_link = bookdetail["volumeInfo"]["imageLinks"]["thumbnail"]
        if "industryIdentifiers" in bookdetail["volumeInfo"]:
            isbns = bookdetail["volumeInfo"]["industryIdentifiers"]
            for i in isbns:
                a = i['type']
                b = i['identifier']
                if a == 'ISBN_13':
                    isbn13a = b
            for i in isbns:
                a = i['type']
                b = i['identifier']
                if a == 'ISBN_10':
                    isbn10a = b
            if isbn13a:
                isbn13 = isbn13a
            else:
                isbn13 = "no ISBN13"
            if isbn10a:
                isbn10 = isbn10a
            else:
                isbn10 = "no ISBN10"
        else:
            isbn13 = "no ISBN13"
            isbn10 = "no ISBN10"

        response = {
                'title': title,

whatchareadn/main/templates/main/index.html
{% extends "base.html" %}

GoogleBooksAPI Key: AIzaSyArFMXNcONVP1TUkIcZ32GNHbZ8xffQSnY

{% block content %}



{% endblock %}

whatchareadn/main/templates/main/library.html
{% extends "base.html" %}
{% load static %}

{% block head %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{% endblock %}

{% block content %}

<div class="page-body">
  <div class="library-header">
    <h1>My Library</h1>
    
    <label for="select-shelf">Shelf</label>  
      {% csrf_token %}
    <select id="select-shelf" class="select-shelf" name="select-shelf" onchange="getShelf()">
      <option value="All">All</option>
      {% for shelf in shelves %}
      <option value="{{ shelf }}">{{ shelf }}</option>
      {% endfor%}
    </select>

    <button id="ed-shel-btn" onclick="showEditCard()">Edit Shelves</button>
  </div>
  
  
  <div id="library-body">
    <!--
  {% for book in library %}
  <div class="card" id="book{{ book.googleid }}">
  
    <a id="card-link" class="detail-btn" btn-id="{{ book.googleid }}" href="#">
      <div class="card-img-box">
        <img src="{{book.image_link}}" />
      </div>
    </a>
 
      <div class="card-body">
        <h3 class="card-title">{{book.title}}</h3>
        <div class="button-row">
          <label for="book-shelf">Shelf</label>
          {% csrf_token %}
          <select id="book-shelf{{ book.googleid }}" class="book-shelf" googleid="{{ book.googleid }}" name="book-shelf" onchange="getShelf()">
            <option value="{{book.shelf}}" selected>{{book.shelf}}</option>
            {% for shelf in shelves %}
            <option value="{{ shelf }}">{{ shelf }}</option>
            {% endfor%}
          </select>


          <button class="read-btn" butt-id="{{ book.googleid }}">Read Book</button>
          <button class="del-btn" butt-id="{{ book.googleid }}">Delete Book</button>
        </div>
      </div>
  </div>
  {% endfor %}
    -->
  </div>
</div>

<div id="modal" class="modal">
  <div id="detail-card" >
    <img id="detail-card-img" src="#" alt="">
    <div class="detail-card-info">
      <div id="detail-card-title"></div>
      <div id="detail-card-authors"></div>
      <div id="detail-card-publisher"></div>
      <div id="detail-card-pubdate"></div>
      <div id="detail-card-isbns"></div>
      <button class="back-btn">X</button>
    </div>
    <div id="detail-card-description"></div>
  </div>
</div>

<div id="edit-shelf" class="modal">
  <div class="edit-shelf-card">
    <input type="text" id="new-shelf-name" placeholder="Name of new shelf">
    <button id="add-new-shelf" class="new-shel-btn" onclick="createShelf()">Create Shelf</button>
    <select id="del-shel-sel" name="del-shel-sel" onchange="showDelete()">
      <option value="" disabled selected>Choose a shelf to delete</option>
      {% for shelf in shelves %}
      {% if shelf.name != "Not on Shelf" %}
      <option value="{{shelf.name}}">{{shelf.name}}</option>
      {% endif %}
      {% endfor %}
    </select>
    <button id="del-shel-btn" onclick="deleteShelf()">Delete</button>
    <button class="close-ed-shel" onclick="hideEditCard()">X</button>
  </div>
</div>

{% endblock%}

{% block js %}
  <script src="{% static 'js/library.js' %}"></script>
{% endblock %}

whatchareadn/main/templates/main/search.html
<!-- vim:fileencoding=utf-8:ft=html:foldmethod=marker
-->

{% extends "base.html" %}
{% load static %}

GoogleBooksAPI Key: AIzaSyArFMXNcONVP1TUkIcZ32GNHbZ8xffQSnY

{% block head %}<!--{{{-->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{% endblock %}<!--}}}-->

{% block content %}

<div id="search-body"><!--{{{-->
  <div class="searchContainer">

    <form method=POST action="{% url 'main:search' %}">
      {% csrf_token %}
      <input type="search" autocomplete="off" placeholder="Search for Books by Title" aria-label="Search" name="titleSearch">
      <button type="submit" name="titlebtn">Search</button>
    </form>
  </div>

  <div id="search-book-body"><!--{{{-->
    {% if stuff %}
    {% for i in stuff.items %}
    {% if i.volumeInfo.authors and i.volumeInfo.imageLinks.thumbnail %}
    <div class="card">


    <a id="card-link" class="detail-btn" btn-id="{{ i.id }}" href="#">
      <div class="card-img-box">
        <img src="{{ i.volumeInfo.imageLinks.thumbnail }}" />
      </div>
    </a>


      <div class="card-body">
        <div class="search-card-body">
          <h2 class="card-title">{{i.volumeInfo.title|truncatechars:40}}</h2>

          <div class="search-card-authors">

            {% for author in i.volumeInfo.authors|slice:":2" %}
              <span><small>-{{author}}</small></span>
            {% endfor %}
            {% if i.volumeInfo.authors|length > 2 %}
            <span>...</span>
            {% endif %}
          </div>


          {% if i.volumeInfo.title in books %}
          <p class="inlibrary">In Library</p>
          {% else %}
          <button class="search-add-btn" id="search-add{{ i.id }}" search-add-id="{{ i.id }}">Add to Library</button>
          {% endif %}

          <p class="search-book-added" id="search-book-added{{ i.id }}"></p>

        </div>
      </div>
    </div>
    {% endif %}
    {% endfor %}
    {% endif%}
  </div><!--}}}-->


</div><!--}}}-->

<div id="modal" class="modal">
  <div id="detail-card" ><!--{{{-->
    <img id="detail-card-img" src="#" alt="">
    <div class="detail-card-info">
      <div id="detail-card-title"></div>
      <div id="detail-card-authors"></div>
      <div id="detail-card-publisher"></div>
      <div id="detail-card-pubdate"></div>
      <div id="detail-card-isbns"></div>
      <button class="back-btn">X</button>
    </div>
    <div id="detail-card-description"></div>
  </div><!--}}}-->
</div>

{% endblock %}

{% block js %}
  <script src="{% static 'js/search.js' %}"></script>
{% endblock %}

whatchareadn/main/templates/main/testpage.html
{% extends "base.html" %}

{% block head %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{% endblock %}

{% block content %}

<div class="page-body">
  <div class="library-header">
    <h1>My Library</h1>
    
    <label for="select-shelf">Shelf</label>  
      {% csrf_token %}
    <select id="select-shelf" class="select-shelf" name="select-shelf" onchange="getShelf()">
      <option value="All">All</option>
      {% for shelf in shelves %}
      <option value="{{ shelf }}">{{ shelf }}</option>
      {% endfor%}
    </select>
  </div>
  
  
  <div id="library-body">
  {% for book in library %}
  <div class="card" id="book{{ book.googleid }}">
  
    <a id="card-link" class="detail-btn" btn-id="{{ book.googleid }}" href="#">
      <div class="card-img-box">
        <img src="{{book.image_link}}" />
      </div>
    </a>
 
      <div class="card-body">
        <h3 class="card-title">{{book.title}}</h3>
        <div class="button-row">
          <label for="book-shelf">Shelf</label>
          {% csrf_token %}
          <select id="book-shelf{{ book.googleid }}" class="book-shelf" googleid="{{ book.googleid }}" name="book-shelf" onchange="getShelf()">
            <option value="{{book.shelf}}">{{book.shelf}}</option>
            {% for shelf in shelves %}
            <option value="{{ shelf }}">{{ shelf }}</option>
            {% endfor%}
          </select>


          <button class="read-btn" butt-id="{{ book.googleid }}">Read Book</button>
          <button class="del-btn" butt-id="{{ book.googleid }}">Delete Book</button>
        </div>
      </div>
  </div>
  {% endfor %}
  </div>
</div>

<div id="modal" class="modal">
  <div id="detail-card" >
    <img id="detail-card-img" src="#" alt="">
    <div class="detail-card-info">
      <div id="detail-card-title"></div>
      <div id="detail-card-authors"></div>
      <div id="detail-card-publisher"></div>
      <div id="detail-card-pubdate"></div>
      <div id="detail-card-isbns"></div>
      <button class="back-btn">X</button>
    </div>
    <div id="detail-card-description"></div>
  </div>
</div>

{% endblock%}

{% block js %}
<script>
// Change Shelf function
  $(document).on('change', '.book-shelf', function(e) {
  e.preventDefault();
  var googleid;
  var shelfname;
  googleid = $(this).attr("googleid");
  //shelfn = $(this).attr("value");
  select = (document).getElementById('book-shelf'+googleid);
  shelfn = select.options[select.selectedIndex].value;

    $.ajax({
        type:'POST',
        url :'/library/change_shelf/',
        data:{
            bookid: googleid,
            shelfn: shelfn,
            csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
        },
        success: function(html){
            getShelf();

        },
    });

});
</script>

<script>
  function getShelf() {
    var shelf;
    shelf = document.getElementById('select-shelf').value;
    library = document.getElementById('library-body');

    $.ajax({
      type: 'POST',
      url: '/library/shelf/',
      data:{
        shelf: shelf,
        csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
      },
      success: function(response){
        console.log(response);
        document.getElementById('library-body').innerHTML = "";
        var temp2 = "";
        var shelfoptions = "";
        var shelfname = "";

        for (var shelf in response.shelves)
        {
            var shelfoption='<option value="'+response.shelves[shelf].name+'">'+response.shelves[shelf].name+'</option>'
            shelfoptions = (shelfoptions + shelfoption)
        }
        for (var book in response.books)
        {
            for (var she in response.shelves)
            {
                if (response.shelves[she].id === response.books[book].shelf_id){
                    var shelfname = response.shelves[she].name;
                }
            }

            var selfshelf = '<option value="'+shelfname+'">'+shelfname+'</option>'
            var shelfselect = (selfshelf + shelfoptions)
            var temp= '<div class="card" id="book'+response.books[book].googleid+'">' +
                        '<a id="card-link" class="detail-btn" btn-id="'+response.books[book].googleid+'" href="#">' +
                          '<div class="card-img-box">' +
                            '<img src="'+response.books[book].image_link+'" />' +
                          '</div>' +
                        '</a>' +
                        '<div class="card-body">' +
                          '<h3 class="card-title">'+response.books[book].title+'</h3>' +
                          '{% csrf_token %}' +
                          '<div class="button-row">' +
                            '<label for="book-shelf">Shelf</label>' +
                            '{% csrf_token %}' +
                            '<select id="book-shelf'+response.books[book].googleid+'" class="book-shelf" googleid="'+response.books[book].googleid+'" name="book-shelf" onchange="getShelf()">'+shelfselect+'</select>' +
                            '<button class="read-btn" butt-id="'+response.books[book].googleid+'">Read Book</button>' +
                            '<button class="del-btn" butt-id="'+response.books[book].googleid+'">Delete Book</button>' +
                          '</div>' +
                        '</div>' +
                      '</div>';
                     
            temp2 = (temp2 + temp);
            document.getElementById('library-body').innerHTML = temp2;
            //window.location.reload();
        }

      },
    });

  };
</script>

<script>
  $('.back-btn').click(function(){
    document.getElementsByTagName('BODY')[0].style.overflow = "auto";
    //document.getElementById('search-body').style.position = "relative";
    document.getElementById('modal').style.visibility = "hidden";

  });
</script>

<!--Info button appends book info to html elements-->
<script>
  //$('.detail-btn').click(function(e){
  $(document).on('click', '.detail-btn', function(e) {
    e.preventDefault();
    var btnid;
    btnid = $(this).attr("btn-id");

    $.ajax({
      type: 'POST',
      url: '/book_detail/',
      data:{
        btnid: btnid,
        csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
      },
      success: function(response){
        console.log(response);

        document.getElementById('detail-card-title').innerHTML = "<strong>Title: </strong>"+response.title;
        document.getElementById('detail-card-authors').innerHTML = "<strong>Authors: </strong>"+response.authors;
        document.getElementById('detail-card-img').src = response.image_link;
        document.getElementById('detail-card-description').innerHTML = response.description;
        document.getElementById('detail-card-publisher').innerHTML = "<strong>Publisher: </strong>"+response.publisher;
        document.getElementById('detail-card-pubdate').innerHTML = "<strong>Date published: </strong>"+response.pubdate;
        document.getElementById('detail-card-isbns').innerHTML = "<strong>ISBNs: </strong>"+response.isbn10+", "+response.isbn13;
        //document.getElementById('search-body').style.position = "fixed";
        document.getElementById('modal').style.visibility = "visible";
        //document.getElementById('library-body').style.display = "none";
        document.getElementsByTagName('BODY')[0].style.overflow = "hidden";
        

      },
    });

  });
</script>

<script>
//$('.del-btn').click(function(e){
  $(document).on('click', '.del-btn', function(e) {
  e.preventDefault();
  var buttid;
  buttid = $(this).attr("butt-id");

    $.ajax({
        type:'POST',
        url :'/library/delete_book/',
        data:{
            buttid: buttid,
            csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
        },
        success: function(html){
            document.getElementById('book' + buttid).remove();
        },
    });

});
</script>
{% endblock %}